//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_SQLSERVER.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;

    public partial class Books
    {
        [Display(Name="#")]
        public int ID { get; set; }
        [Display(Name = "Nombre del lirbo")]
        public string nameBook { get; set; }
        [Display(Name = "Autor del libro")]
        public string author { get; set; }
        [Display(Name = "Fecha de lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime date { get; set; }
    }
}
